apiVersion: v1
kind: Pod
metadata:
  name: my-test-pod
  namespace: my-namespace
spec:
  containers:
  - name: test
    image: registry.cluster.wik.cloud/public/echo
    ports:
    - containerPort: 8080