apiVersion: v1
kind: ReplicaSet
metadata:
  name: my-test-replicaset
  namespace: my-namespace
spec:
  replicas: 4
  containers:
  - name: test
    image: registry.cluster.wik.cloud/public/echo
    ports:
    - containerPort: 8080